### ISSUE TITLE
ERROR in Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by davidafuller01** [emadalam/tvml-catalog-using-atvjs#1]
I'm a node.js newbie, so excuse me in advance if my suggestion isn't quite right.

I was seeing the following error from the gulp console:
`ERROR in Cannot find module 'handlebars'` + plus /path/index.js for all page templates (e.g. `ERROR in Cannot find module 'handlebars' @ ./web/app/pages/form/index.js 11:16-41`) when firing up the Xcode simulator.

To resolve:
1. `npm install -g handlebars`
2. `cat package.json in /tvml-catalog-using-atvjs-master` (handlebars not shown in devDependencies or dependencies)
3. `npm install --save handlebars`
4. `cat package.json in /tvml-catalog-using-atvjs-master` (handlebars now shown in dependencies)
5. restart Xcode simulator / successful start of application

You might consider updating the main package.json as appropriate.

**Comment by emadalam** [comment]
I have explicitly added `handlebars` to the `package.json` file as a dependency.

`npm` prior to `version 3`, would automatically install the [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/), and `handlebars` was already defined as a peer dependency by the [handlebars-loader](https://github.com/altano/handlebars-loader) that is used in the project. However starting version 3 onwards, [npm doesn't auto-install any of the peerDependencies](http://blog.npmjs.org/post/110924823920/npm-weekly-5).

As I am still using a lower version of npm, I couldn't catch this. Thanks for pointing this out @davidafuller01 :+1:
